name: Build Docker Multiarch

on: push

env:
  IMAGE_NAME: docker.pkg.github.com/premist/ruby-prometheus-exporter-example:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker login
        run: echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

      - name: Build multiarch image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.IMAGE_NAME }} --load .

      - name: Push multiarch image
        run: docker push ${{ env.IMAGE_NAME }}
